export {default as Hero} from "./Hero";
export {default as Boxes} from "./Boxes";
export {default as Trending} from "./Trending";
export {default as TopGame} from "./TopGame";
export {default as Categories} from "./Categories";
export {default as Subscribe} from "./Subscribe ";
export {default as OurShop} from "./OurShop";
export {default as Filter} from "./Filter";
export {default as GameShop} from "./GameShop";
export {default as ProductsDetails} from "./ProductsDetails";
export {default as ContactUs} from "./ContactUs";
export {default as ContactForm} from "./ContactForm";