export { default as Nav} from './Nav'
export { default as Container} from './Container'
export { default as Box} from './Box'
export { default as Head} from './Head'
export { default as TrendingCards} from './TrendingCards'
export { default as GameCards} from './GameCards'
export { default as CategoriesCard} from './CategoriesCard'
export {default as Footer} from './Footer'
export {default as Heading} from './Heading'
export {default as Modern} from './Modern'
export {default as ContactContent} from './ContactContent'
export {default as ContactInfo} from './ContactInfo'